replicaCount: 2

image:
  repository: your-ecr-repository/payment-gateway-ms
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: "1"
    memory: 512Mi
  requests:
    cpu: "0.5"
    memory: 256Mi

environment:
  SPRING_PROFILES_ACTIVE: dev
  DATABASE_URL: jdbc:postgresql://dev-db-url:5432/paymentdb