replicaCount: 2

image:
  repository: your-ecr-repository/payment-gateway-ms
  tag: test
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: "0.5"
    memory: 512Mi

environment:
  SPRING_PROFILES_ACTIVE: test
  DATABASE_URL: jdbc:postgresql://test-db-url:5432/paymentdb
